import { useRouter } from "next/router.js"
import { useCallback } from "react"
import { useContext } from "..//../components/ContextProvider"
import Head from "next/head"
import { Form } from "../../components/TaskEditingForm"

const CreateTaskPage = () => {
  const { createTask, currentCategory } = useContext()
  const router = useRouter()
  const handleSubmit = useCallback(
    ({ content }) => {
      createTask(content, currentCategory)
      router.push("/")
    },
    [router, createTask, currentCategory]
  )

  return (
    <div>
      <Head>
        <title>Creating a new task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form onSubmit={handleSubmit} title="Add task" />
    </div>
  )
}

export default CreateTaskPage
