import { useRouter } from "next/router.js"
import { useCallback } from "react"
import { useContext } from "..//../components/ContextProvider"
import Head from "next/head"
import { Form } from "../../components/TaskEditingForm"

const CreateTodoPage = () => {
  const { createTodo } = useContext()
  const router = useRouter()
  const handleSubmit = useCallback(
    ({ name }) => {
      createTodo(name)
      router.push("/")
    },
    [router, createTodo]
  )

  return (
    <div>
      <Head>
        <title>Creating a new list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form onSubmit={handleSubmit} name="name" title="Add a list" />
    </div>
  )
}

export default CreateTodoPage
